# Generated by Django 4.2 on 2024-03-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskNumber", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Clark", "Clark"),
                            ("Turner", "Turner"),
                            ("Fell", "Fell"),
                            ("Chapel", "Chapel"),
                            ("Kinser", "Kinser"),
                            ("Big Bear", "Big Bear"),
                            ("Shower Houses", "Shower Houses"),
                        ],
                        max_length=200,
                    ),
                ),
                ("subLocation", models.CharField(choices=[], max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "typeOfIssue",
                    models.CharField(
                        choices=[
                            ("Plumbing", "Plumbing"),
                            ("Electrical", "Electrical"),
                            ("Furniture", "Furniture"),
                            ("Structural", "Structural"),
                            ("Other", "Other - Please Explain"),
                        ],
                        max_length=200,
                    ),
                ),
                ("assignedWorker", models.CharField(blank=True, max_length=200)),
                ("isClosed", models.BooleanField(default=False)),
                ("photo", models.ImageField(upload_to="requestPhotos/")),
            ],
        ),
    ]
