# Generated by Django 4.2 on 2024-03-29 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_number", models.IntegerField()),
                ("submitter_name", models.CharField(max_length=200)),
                ("contact_info", models.CharField(max_length=200)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Clark", "Clark"),
                            ("Turner", "Turner"),
                            ("Fell", "Fell"),
                            ("Chapel", "Chapel"),
                            ("Kinser", "Kinser"),
                            ("Big Bear", "Big Bear"),
                            ("Shower Houses", "Shower Houses"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "sub_location",
                    models.CharField(
                        choices=[
                            ("Room 1-1", "Room 1-1"),
                            ("Room 2-1", "Room 2-1"),
                            ("Room 3-1", "Room 3-1"),
                        ],
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "type_of_issue",
                    models.CharField(
                        choices=[
                            ("Plumbing", "Plumbing"),
                            ("Electrical", "Electrical"),
                            ("Furniture", "Furniture"),
                            ("Structural", "Structural"),
                            ("Other", "Other - Please Explain"),
                        ],
                        max_length=200,
                    ),
                ),
                ("assigned_worker", models.CharField(blank=True, max_length=200)),
                ("is_closed", models.BooleanField(default=False)),
                ("close_note", models.TextField(blank=True)),
                ("close_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkRequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="qrc_app/request_photos/")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qrc_app.workrequest",
                    ),
                ),
            ],
        ),
    ]
