# Generated by Django 4.2 on 2024-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrequest",
            name="close_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="workrequest",
            name="description",
            field=models.TextField(),
        ),
    ]
