# Generated by Django 4.2 on 2024-03-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workrequest",
            name="photo",
        ),
        migrations.CreateModel(
            name="WorkRequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="request_photos/")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qrc_app.workrequest",
                    ),
                ),
            ],
        ),
    ]
