# Generated by Django 4.2 on 2024-03-26 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0002_remove_workrequest_photo_workrequestimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workrequest",
            old_name="assignedWorker",
            new_name="assigned_worker",
        ),
        migrations.RenameField(
            model_name="workrequest",
            old_name="isClosed",
            new_name="is_closed",
        ),
        migrations.RenameField(
            model_name="workrequest",
            old_name="subLocation",
            new_name="sub_location",
        ),
        migrations.RenameField(
            model_name="workrequest",
            old_name="name",
            new_name="submitter_name",
        ),
        migrations.RenameField(
            model_name="workrequest",
            old_name="taskNumber",
            new_name="task_number",
        ),
        migrations.RenameField(
            model_name="workrequest",
            old_name="typeOfIssue",
            new_name="type_of_issue",
        ),
    ]
