# Generated by Django 4.2 on 2024-04-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0003_staffaccount_rentalgroupaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalgroupaccount",
            name="is_rental_group",
            field=models.BooleanField(default=False),
        ),
    ]
