# Generated by Django 4.2 on 2024-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0003_alter_workrequest_close_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrequest",
            name="description",
            field=models.TextField(),
        ),
    ]
