# Generated by Django 4.2 on 2024-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0003_rename_assignedworker_workrequest_assigned_worker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workrequest",
            name="sub_location",
            field=models.CharField(
                choices=[
                    ("Room 1-1", "Room 1-1"),
                    ("Room 2-1", "Room 2-1"),
                    ("Room 3-1", "Room 3-1"),
                ],
                max_length=200,
            ),
        ),
    ]
