# Generated by Django 4.2 on 2024-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrc_app", "0004_alter_rentalgroupaccount_is_rental_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalgroupaccount",
            name="is_rental_group",
            field=models.BooleanField(default=True),
        ),
    ]
